### ISSUE TITLE
Gazelle fails resolving generated packages in private repos

### ISSUE THREAD

**Issue by guw** [bazel-contrib/bazel-gazelle#2127]
I have a repository where Gazelle fails to run cleanly. While `go mod tidy -e` works I am struggling with failing Gazelle runs.

Setup:
- private repo at `github.com/private/foo`
- Bazel workspace at `bar/` within that repo

`bar/MODULE.bazel`:

```Starlark
go_deps.config(
    go_env = {
        "GOPRIVATE": "github.com/private",
        "GOPROXY": "...",
        "GOWORK": "off",
    },
)
go_deps.from_file(go_mod = "//:go.mod")
```

Git configuration:

```
$ git config -l --show-origin | grep instead                              
file:/home/username/.gitconfig      url.git@github.com:.insteadof=https://github.com/
```

This might be important because Git auth is setup using SSH but not https.

```Shell
INFO: Running command line: bazel-bin/gazelle
gazelle: finding module path for import github.com/private/foo/bar/proto/whatever/v1: go: -d flag is deprecated. -d=true is a no-op
go: downloading github.com/private/foo/bar v0.0.0-...
github.com/private/foo@...: verifying module: github.com/private/foo@...: reading https://sum.golang.org/lookup/github.com/private/foo@...: 404 Not Found
        server response:
        not found: github.com/private/foo@...: invalid version: git ls-remote -q origin in /tmp/gopath/pkg/mod/cache/vcs/checksum: exit status 128:
                fatal: could not read Username for 'https://github.com': terminal prompts disabled
        Confirm the import path was entered correctly.
        If this is a private repository, see https://golang.org/doc/faq#git_https for additional information.
```

There seems to be a couple of issues at play here.

1. `github.com/private/foo` is a private repo
2. `github.com/private/foo/bar/proto/whatever/v1` is generated from poto file
3. there is an `empty.go` file at `bar/proto/whatever/v1` - it seems to be ignored by Gazelle but `go mod tidy` is happy
4. `GOPRIVATE` is defined in `bar/MODULE.bazel` but it seems to be ignored bz Gazelle
5. It should not attempt to hit `sum.golang.org` because `GONOSUMDB` is implied from `GOPRIVATE`. Perhaps another indicator that `GOPRIVATE` is not set?
6. There is a Git config override to use SSH instead of https for the Git URL, which seems to be ignored by the `git ls-remote` remote command executed by Gazelle

Note, the `empty.go` files workaround mentioned in https://github.com/bazel-contrib/rules_go/issues/2262 helped with `go mod tidy`, which does run fine (using `go_env` from `MODULE.bazel`)

**Comment by fmeum** [comment]
Thanks for the detailed report. Looks like we "just" have to fix 3. - 7. one by one? Do you already have a lead on some of these issues?

**Comment by guw** [comment]
@fmeum Is my assumption wrong that `bazel run //:gazelle` should apply `go_env`? Because when I manually set it (`export GOPRIVATE=github.com/private`) Gazelle seems to work.

**Comment by fmeum** [comment]
It should and if it doesn't, we should fix that.

**Comment by fmeum** [comment]
Looks like I just forgot to do this after https://github.com/bazel-contrib/bazel-gazelle/commit/f590ca1488eff5063a9549a3edba8266a6ce6134.

Would you be willing to send a PR that prepends the constant here: https://github.com/bazel-contrib/bazel-gazelle/blob/dc5cce4501e56d13a5383d860970caa0f42421d7/def.bzl#L144?

**Comment by guw** [comment]
It looks like item 6 is still a problem even for `bazel build`. Any possibility that a global `~/.gitconfig` is ignored due to sandboxing? I found issue reports in Bazel which imply that special logic was implemented to deal with that but I could not find traces in source.

**Comment by guw** [comment]
> Any possibility that a global `~/.gitconfig` is ignored due to sandboxing?

Not due to sandboxing but due to humans messing with action environment. In case anyone else hits this, check that you don't have `--action_env=HOME=/tmp` somewhere in a config profile.

https://github.com/bazelbuild/bazel/issues/18334
